keys:
  # Personal development key (from ~/.config/sops/age/keys.txt)
  - &bruno age1yehyuhgvcp6csvvvg79luvqw0akymdng8wflu2g9kfwhxxnjuujsjw4ae7

  # Host keys (add after first boot using ssh-to-age)
  # - &roubaix age1...

creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *bruno
          # - *roubaix  # Uncomment after initial setup
